In [44]:
import torch
import numpy as np
import time
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [36]:
randint = torch.randint(-500 , 500 ,(6,))
randint

tensor([ 478, -410,  131,  477,  315,  353])

In [37]:
tensor = torch.tensor([[0.1,0.2],[0.3,0.4],[1,6]])
tensor

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [1.0000, 6.0000]])

In [38]:
#these are Floating point numbers
zeros = torch.zeros(2,3)
zeros
ones = torch.ones(5,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
arange = torch.arange(6)
arange

tensor([0, 1, 2, 3, 4, 5])

In [40]:
linspace = torch.linspace(start = 5, end = 10, steps = 3)
linspace

tensor([ 5.0000,  7.5000, 10.0000])

In [41]:
logspace = torch.logspace(-10 , 10 ,3)
logspace

tensor([1.0000e-10, 1.0000e+00, 1.0000e+10])

In [42]:
eye = torch.eye(6)
eye

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])