In [1]:
import torch
import numpy as np
import time
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [2]:
randint = torch.randint(-500 , 500 ,(6,))
randint

tensor([-334,  413, -434, -408,  395,  352])

In [3]:
tensor = torch.tensor([[0.1,0.2],[0.3,0.4],[1,6]])
tensor

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [1.0000, 6.0000]])

In [4]:
#these are Floating point numbers
zeros = torch.zeros(2,3)
zeros
ones = torch.ones(5,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
arange = torch.arange(6)
arange

tensor([0, 1, 2, 3, 4, 5])

In [6]:
linspace = torch.linspace(start = 5, end = 10, steps = 3)
linspace

tensor([ 5.0000,  7.5000, 10.0000])

In [7]:
logspace = torch.logspace(-10 , 10 ,3)
logspace

tensor([1.0000e-10, 1.0000e+00, 1.0000e+10])

In [8]:
eye = torch.eye(6)
eye

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [11]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.4f}")

0.0000


In [14]:
#Comparing running time between Gpu and Cpu
torch_rand1 = torch.rand(100 , 100 , 100 , 100).to(device)
torch_rand2 = torch.rand(100 , 100 , 100 , 100).to(device)
np_array1 = torch.rand(100 , 100 , 100 , 100)
np_array2 = torch.rand(100 , 100 , 100 , 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
Elapsed_time = end_time - start_time
print(f"{Elapsed_time:9f}")

start_time = time.time()
rand = np.multiply(np_array1,np_array2)
end_time = time.time()
Elapsed_time = end_time - start_time
print(f"{Elapsed_time:9f}")




 0.371587
 0.107005


In [16]:
#defining a probability tensor
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities, 10, True)
samples

tensor([1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [17]:
#concatinating two tensors into one and this can be used when we are generating text, given a context
tensor = torch.tensor([1,2,3,4,5])
#dim is a parameter used in the torch.cat function to specify the dimension along which the tensors should be concatenated.
outputt = torch.cat((tensor, torch.tensor([5])), dim = 0)         
outputt

tensor([1, 2, 3, 4, 5, 5])

In [20]:
#tril - triangle lower
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
out = 